### ISSUE TITLE
Add support for compose-jb

### ISSUE THREAD

**Issue by dragossusi** [chrisbanes/snapper#5]
**Is your feature request related to a problem? Please describe.**
I want to use this library with pager from accompanist in my Compose for Desktop app.

**Describe the solution you'd like**
Add support for `compose-jb` to be able to use this as a multiplatform library, the code looks to not depend on android only code so it should be possible.

**Describe alternatives you've considered**
If not, I can fork this and make a new version that supports Compose for Desktop.

**Additional context**
I have migrated all my android app from xml + fragments to compose only to make my app work for desktop as well and it works well, but I need a Pager and I can't use accompanist because it supports Android only.

**Comment by chrisbanes** [comment]
Thanks for the report. Yeah this is something I've thought about, but it's actually pretty difficult to have a single build using the same source files, but with different plugins.

I tried having 2 modules (one JB, one Android) and then setting the source sets to use `shared/src/blah/Snapper.kt`, but Android Studio didn't like it. I think my next attempt will be to attach a copy task to Compose JB's compile step, to copy over the 'Android' source files to a temporary/gen location.

**Comment by cjbrooks12** [comment]
You shouldn't need to copy sources and use multiple plugins. Just by converting to a Kotlin Multiplatform project with Android support and using the `org.jetbrains.compose` Gradle plugin instead of the Android plugin's `buildFeatures`, the artifacts will be available for use by both Android and Desktop. 

Here's the [build.gradle.kts](https://github.com/copper-leaf/thistle/blob/main/thistle-compose-ui/build.gradle.kts) for a library I recently published that does exactly this. The repo also has example sub-projects that apply the normal Android/Compose or Desktop configurations, showing that the library can be published with JB compose, but used on Android without needing the Android app to be MPP/JB-compose.

**Comment by dragossusi** [comment]
@cjbrooks12 the jetbrains project uses an older version of compose, you will not be able to use this library on the latest compose version for Android, it's better to have 2 projects for each

**Comment by zacharee** [comment]
I copied the library code into my compose-jb project to test it out, but snapping doesn't work. I'm pretty sure it's related to [this issue](https://github.com/JetBrains/compose-jb/issues/1423), which means `performFling()` never gets called.

**Comment by chrisbanes** [comment]
@zacharee yeah that looks like a hard stopper for this. The flinging implementation on Desktop looks like it completely bypasses all of the `scrollable` state calls.
